version: "3.7"

services: 
  wtf_database:
    image: postgres
    container_name: wtf_database
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=wtfpass
      - POSTGRES_DB=wtf
    volumes: 
      - pgdata:/data/postgres
      

  wtf_app:
    build: .
    container_name: wtf_app
    entrypoint: ["npm","run","dev"]
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    depends_on:
      - wtf_database
    links:
      - wtf_database
      
volumes: 
  pgdata: 
    driver: local
